// This configuration is placeholder and will be replaced by the Studio environment.
// Do not edit this file manually.

const firebaseConfig = {
  "projectId": "studio-1353078452-edea5",
  "appId": "1:670280415506:web:2202bfb9d00fcc80e3dbcb",
  "apiKey": "AIzaSyAukvXJXH-J7gaLgsw8k6ng9ype3pxOfuI",
  "authDomain": "studio-1353078452-edea5.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "670280415506"
};

export default firebaseConfig;
